#!/usr/bin/env python3
"""Validate wiki frontmatter against schema.md.

Walks wiki/*.md, parses YAML frontmatter, reports missing required fields
per page type plus missing common retrieval fields (§1.0). Stdlib only.

Usage: python3 tools/validate_frontmatter.py
Output: wiki/_schema_audit.md
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

WIKI_ROOT = Path(__file__).resolve().parent.parent / "wiki"
OUTPUT = WIKI_ROOT / "_schema_audit.md"

SKIP_FILES = {"_log.md", "_absorb_log.json", "_backlinks.json", "_schema_audit.md"}

COMMON_REQUIRED = ["title", "type", "summary", "last_updated"]

TYPE_REQUIRED = {
    "product":           ["product", "states_active"],
    "state-meta":        ["state", "products_active"],
    "multistate":        ["product", "page", "scope"],
    "product-state":     ["product", "state", "page", "scope"],
    "product-state-sub": ["product", "state", "parent", "sub", "scope"],
    "form":              ["form_id", "product", "scope"],
    "coverage":          ["coverage_id", "products", "scope"],
    "concept":           ["concept_id", "products", "scope"],
    "comparison":        ["comparison_type"],
    "index":             [],
}

VALID_SCOPES = {"multistate", "state-specific", "state-override", "cross-product"}


def parse_frontmatter(text):
    """Return (dict, None) or (None, error). Minimal YAML subset."""
    if not text.startswith("---\n"):
        return None, "no frontmatter"
    end = text.find("\n---", 4)
    if end == -1:
        return None, "unterminated frontmatter"
    block = text[4:end]

    result = {}
    current_key = None
    for raw in block.split("\n"):
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        # List continuation: "  - item"
        if line.startswith(("  - ", "- ")):
            val = line.split("- ", 1)[1].strip().strip('"').strip("'")
            if current_key is not None:
                if not isinstance(result.get(current_key), list):
                    result[current_key] = []
                result[current_key].append(val)
            continue
        m = re.match(r"^([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        current_key = key
        if val == "":
            result[key] = None
        elif val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            result[key] = [] if not inner else [
                x.strip().strip('"').strip("'") for x in inner.split(",")
            ]
        elif val in ("true", "false"):
            result[key] = val == "true"
        elif val == "null":
            result[key] = None
        else:
            result[key] = val.strip('"').strip("'")
    return result, None


def is_missing(fm, field):
    if field not in fm:
        return True
    v = fm[field]
    if v is None or v == "":
        return True
    if isinstance(v, list) and len(v) == 0:
        return True
    return False


def main():
    gaps_by_page = {}
    type_counts = defaultdict(int)
    total = 0
    issues_summary = defaultdict(int)

    for md in sorted(WIKI_ROOT.rglob("*.md")):
        if md.name in SKIP_FILES:
            continue
        rel = md.relative_to(WIKI_ROOT)
        text = md.read_text(encoding="utf-8")
        fm, err = parse_frontmatter(text)
        total += 1

        if err:
            gaps_by_page[str(rel)] = [f"PARSE: {err}"]
            issues_summary["parse-error"] += 1
            continue

        page_type = fm.get("type") or "<unknown>"
        type_counts[page_type] += 1
        missing = []

        for field in COMMON_REQUIRED:
            if is_missing(fm, field):
                missing.append(f"missing:{field}")
                issues_summary[f"missing:{field}"] += 1

        for field in TYPE_REQUIRED.get(page_type, []):
            if is_missing(fm, field):
                missing.append(f"missing:{field}")
                issues_summary[f"missing:{field}"] += 1

        if "scope" in fm and fm["scope"] not in VALID_SCOPES and fm["scope"] is not None:
            missing.append(f"invalid-scope:{fm['scope']}")
            issues_summary["invalid-scope"] += 1

        if missing:
            gaps_by_page[str(rel)] = missing

    # Report
    lines = [
        "# Schema Audit Report",
        "",
        f"_Generated by `tools/validate_frontmatter.py`_",
        "",
        f"- Pages scanned: **{total}**",
        f"- Pages with gaps: **{len(gaps_by_page)}**",
        f"- Pages clean: **{total - len(gaps_by_page)}**",
        "",
        "## Page counts by `type`",
        "",
        "| Type | Count |",
        "|---|---|",
    ]
    for t, c in sorted(type_counts.items()):
        lines.append(f"| `{t}` | {c} |")

    lines += ["", "## Issue frequency", "", "| Issue | Count |", "|---|---|"]
    for issue, c in sorted(issues_summary.items(), key=lambda x: -x[1]):
        lines.append(f"| `{issue}` | {c} |")

    lines += ["", "## Gaps by page", ""]
    if not gaps_by_page:
        lines.append("_No gaps found._")
    else:
        lines.append("| Page | Missing / issues |")
        lines.append("|---|---|")
        for path, missing in sorted(gaps_by_page.items()):
            lines.append(f"| `{path}` | {', '.join(missing)} |")
    lines.append("")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    print(f"{len(gaps_by_page)} / {total} pages have gaps")
    return 0 if not gaps_by_page else 0  # non-failing; report is the output


if __name__ == "__main__":
    sys.exit(main())
